name: RunPod Pod Scheduler

on:
  schedule:
    - cron: '20 12 * * *'   # 5:50pm IST (start pod)
    - cron: '36 12 * * *'   # 6:06pm IST (stop pod)

jobs:
  start-pod:
    if: github.event.schedule == '20 12 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Start RunPod Pod
        run: |
          curl -X POST "https://api.runpod.io/graphql" \
          -H "Authorization: ${{ secrets.RUNPOD_API_KEY }}" \
          -H "Content-Type: application/json" \
          --data '{"query":"mutation { podResume(id: \"hl2kbew840rd5b\") { id status } }"}'

  stop-pod:
    if: github.event.schedule == '36 12 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Stop RunPod Pod
        run: |
          curl -X POST "https://api.runpod.io/graphql" \
          -H "Authorization: ${{ secrets.RUNPOD_API_KEY }}" \
          -H "Content-Type: application/json" \
          --data '{"query":"mutation { podStop(id: \"hl2kbew840rd5b\") { id status } }"}'
