name: RunPod Stop Pod

on:
  schedule:
    - cron: '30 4 * * *'   # 10:00 AM IST (04:30 UTC)

jobs:
  stop-pod:
    runs-on: ubuntu-latest
    steps:
      - name: Stop RunPod Pod
        run: |
          curl -X POST "https://api.runpod.io/graphql" \
          -H "Authorization: ${{ secrets.RUNPOD_API_KEY }}" \
          -H "Content-Type: application/json" \
          --data '{"query":"mutation { podStop(id: \"hl2kbew840rd5b\") { id status } }"}'
